// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcOoMzAZM7MsQrPwuetsJ6q5zuD28leGw',
    appId: '1:108752801632:web:6eda234e0ca9c8ccd09805',
    messagingSenderId: '108752801632',
    projectId: 'rise-2022',
    authDomain: 'rise-2022.firebaseapp.com',
    storageBucket: 'rise-2022.appspot.com',
    measurementId: 'G-13SK3MHW8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgc9IE4ZiOM4ftAJEDRhtWNyl3I4Qa70',
    appId: '1:108752801632:android:5039ba30db61efb3d09805',
    messagingSenderId: '108752801632',
    projectId: 'rise-2022',
    storageBucket: 'rise-2022.appspot.com',
  );
}
