# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "RISE 2022 Book of Mormon Reading Tracker"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:108752801632:web:6eda234e0ca9c8ccd09805",
            firebase_cli_token: "1//04QQr7Gzdda41CgYIARAAGAQSNgF-L9IrDs_UeeR7S1HNgymEVBlmohqv_OAAa6rRTE2vF4_sJBUVgZOx8o9Isp7Zh0P9xsxtUg",
            testers: "m0smith@gmail.com,mjabas@gmail.com",
            release_notes: "<Enter the release notes>",
            firebase_cli_path: "/usr/local/bin/firebase",
            android_artifact_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end
